pipeline {
  agent any
  tools {nodejs "node16.17"}
  environment {
    S3bucket_name = 'skye20221020tf'
    repo_path = '/var/lib/jenkins/workspace/skyefront1007/out'
  }
  stages {
  stage('SonarCloud') {
  environment {
    SCANNER_HOME = tool 'SonarQubeScanner'
    ORGANIZATION = "skye1349"
    PROJECT_NAME = "skye1349_houzez-app"
  }
  steps {
    withSonarQubeEnv('SonarCloudOne') {
        sh '''$SCANNER_HOME/bin/sonar-scanner -Dsonar.organization=$ORGANIZATION \
        -Dsonar.java.binaries=build/classes/java/ \
        -Dsonar.projectKey=$PROJECT_NAME \
        -Dsonar.exclusions=**/package-lock.json/**\
        -Dsonar.sources=.'''
         }
        }
      }
      
    stage('Install Packages') {
      steps {
        sh 'npm install'
      }
    }
    stage('Test and Build') {
      parallel {
        stage('Run Tests') {
          steps {   
            sh 'echo no tests now'
             sh 'npm run test-c'
          }
        }
        stage('Create Build Artifacts') {
          steps {
            sh 'npm run build'
          }
        }
      }
    }

    stage('Upload') {
        steps {
            echo 'Deploying to AWS s3 bucket.'
            withAWS(region:'ap-southeast-2',credentials:'9f5a5bbb-f9c9-45ff-abcc-45157ed47fcc') {
                sh 'aws s3 sync $repo_path s3://skye20221020tf/'
            }
        };
    }
  }    
}
